version: '3'
services:
  app:
    image: node:20
    command: yarn dev --port 3000 --host
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app

  api:
    image: php:8.3
    command: php -S 0.0.0.0:8080
    working_dir: /var/app/www
    ports:
      - 8080:8080
    volumes:
      - ./simpleserver:/var/app/www